version: "3.9"
services:
  postgres:
    container_name: kaspdb
    restart: always
    build:
      context: Server/sql
      dockerfile: Server/sql/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: kaspdb
    ports:
      - "5434:5432"
  app:
    container_name: kaspserver
    build:
      context: Server
      dockerfile: Server/Dockerfile
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: kapsdb
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  front:
    container_name: kaspfront
    build:
      context: Client
      dockerfile: Client/Dockerfile
    restart: always
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
